name: testing_github_action_name

on: push

jobs:
  github_action_job:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run a py script
      run: python test.py
